# Generated by Django 3.1.3 on 2021-07-14 14:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 7, 14, 14, 43, 22, 774810, tzinfo=utc)),
        ),
    ]
