# Generated by Django 3.1.3 on 2021-07-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0002_auto_20210714_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='published_date',
            field=models.DateTimeField(verbose_name='Wed Jul 14 20:16:20 2021'),
        ),
    ]
