# Generated by Django 3.2.5 on 2021-07-14 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0004_auto_20210714_2017'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
