# Generated by Django 3.1.3 on 2021-07-27 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database_api', '0006_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
